apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus-logging
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - name: prometheus
        image: bitnami/prometheus
        ports:
        - containerPort: 9090
          targetPort: 9090
      
      #   volumeMounts:
      #   - name: varlog
      #     mountPath: /var/log
      #   - name: varlibdockercontainers
      #     mountPath: /var/lib/docker/containers
      #     readOnly: true
      # terminationGracePeriodSeconds: 30
      # volumes:
      # - name: varlog
      #   hostPath:
      #     path: /var/log
      # - name: varlibdockercontainers
      #   hostPath:
      #     path: /var/lib/docker/containers
