apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nexus-cluster
  region: us-east-1

nodeGroups:
  - name: ng-2
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      publicKeyPath: C:\Users\sivav\.ssh\id_rsa.pub
